spring:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:marketdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
flyway:
  user: sa
  password: password
  url: jdbc:h2:mem:marketdb
